### ISSUE TITLE
using both --snv and --indel

### ISSUE THREAD

**Issue by hliang** [misshie/UCSC2VCF#1]
An error would occur if both `--snv` and `--indel` (to output both snp and indel) are supplied in the command line:
```
$ ~/pkg/UCSC2VCF/ucsc2vcf.rb --indel --snv --reference hg19.2bit test.txt
/home/ubuntu/pkg/UCSC2VCF/ucsc2vcf.rb:92:in `refseq': undefined method `find_by_interval' for nil:NilClass (NoMethodError)
        from /home/ubuntu/pkg/UCSC2VCF/ucsc2vcf.rb:124:in `locus_insertion'
        from /home/ubuntu/pkg/UCSC2VCF/ucsc2vcf.rb:201:in `locus'
        from /home/ubuntu/pkg/UCSC2VCF/ucsc2vcf.rb:223:in `block in run'
        from /home/ubuntu/pkg/UCSC2VCF/ucsc2vcf.rb:222:in `each_line'
        from /home/ubuntu/pkg/UCSC2VCF/ucsc2vcf.rb:222:in `each_line'
        from /home/ubuntu/pkg/UCSC2VCF/ucsc2vcf.rb:222:in `each'
        from /home/ubuntu/pkg/UCSC2VCF/ucsc2vcf.rb:222:in `run'
        from /home/ubuntu/pkg/UCSC2VCF/ucsc2vcf.rb:253:in `<main>'
```
The issue seemed to be fixed if I change:
```
    def initialize(opts)
      @opts = opts
      unless opts[:snv]
        load_reference
      end
    end
```
to:
```
    def initialize(opts)
      @opts = opts
      load_reference
    end
```

**Comment by misshie** [comment]
Thank you so much for your comment. Finally, I committed the following code. Only indels require a reference sequence.
```
if opts[:indel]
  load_reference
end
```
